export const players = [
    {number:1,name: "Peter Pekarik", position: 'D', matches: '3', time:'270:00',goals: "5", assist: "0", yellowcard:"3", redcard:"0"},
    {number:2,name: "Róbert Boženík", position: 'Ú', matches: '2', time:'112:05',goals: "1", assist: "1", yellowcard:"1", redcard:"0"},
    {number:3,name: "Peter Pekarik", position: 'D', matches: '4', time:'270:00',goals: "6", assist: "0", yellowcard:"0", redcard:"0"},
    {number:4,name: "Peter Pekarik", position: 'D', matches: '5', time:'270:00',goals: "1", assist: "0", yellowcard:"0", redcard:"0"},
    {number:5,name: "Peter Pekarik", position: 'D', matches: '32', time:'270:00',goals: "1", assist: "0", yellowcard:"1", redcard:"0"},
    {number:6,name: "Peter Pekarik", position: 'D', matches: '2', time:'270:00',goals: "1", assist: "0", yellowcard:"5", redcard:"0"},
    {number:7,name: "Peter Pekarik", position: 'D', matches: '5', time:'270:00',goals: "1", assist: "0", yellowcard:"0", redcard:"0"},
    {number:8,name: "Peter Pekarik", position: 'D', matches: '4', time:'270:00',goals: "1", assist: "0", yellowcard:"1", redcard:"0"},
    {number:9,name: "Peter Pekarik", position: 'D', matches: '5', time:'270:00',goals: "1", assist: "0", yellowcard:"1", redcard:"0"},
    {number:10,name: "Peter Pekarik", position: 'D', matches: '6', time:'270:00',goals: "1", assist: "0", yellowcard:"1", redcard:"0"},
    {number:11,name: "Peter Pekarik", position: 'D', matches: '7', time:'270:00',goals: "1", assist: "0", yellowcard:"32", redcard:"0"},
    {number:12,name: "Peter Pekarik", position: 'D', matches: '8', time:'270:00',goals: "1", assist: "0", yellowcard:"0", redcard:"0"},
    {number:13,name: "Peter Pekarik", position: 'D', matches: '1', time:'270:00',goals: "1", assist: "0", yellowcard:"1", redcard:"0"},
    {number:14,name: "Peter Pekarik", position: 'D', matches: '13', time:'270:00',goals: "1", assist: "0", yellowcard:"1", redcard:"0"},
    {number:15,name: "Peter Pekarik", position: 'D', matches: '23', time:'270:00',goals: "10", assist: "0", yellowcard:"0", redcard:"0"},
    {number:16,name: "Peter Pekarik", position: 'D', matches: '35', time:'270:00',goals: "1", assist: "0", yellowcard:"2", redcard:"0"},
    {number:17,name: "Peter Pekarik", position: 'D', matches: '43', time:'270:00',goals: "1", assist: "0", yellowcard:"2", redcard:"0"},
    {number:18,name: "Peter Pekarik", position: 'D', matches: '1', time:'270:00',goals: "1", assist: "0", yellowcard:"2", redcard:"0"},
  ];